const express = require('express');
const http = require('http');
const { url } = require('inspector');
const { type, hostname } = require('os');
const readXlsxFile = require('read-excel-file/node');
const { readSheetNames } = require('read-excel-file/node');
const path = require('path');

function getResultz(p) {
  const url = 'http://api.cup2022.ir/api/v1/match';

  const options2 = {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
  };
  const dataz = JSON.stringify({
    email: 'anthony.mota5@yahoo.com',
    password: 'Zacatecas!415',
  });

  const reqq = http.request(
    'http://api.cup2022.ir/api/v1/user/login',
    options2,
    (ress) => {
      let rawData = '';
      ress.on('data', (dta) => {
        rawData += dta;
        const token = JSON.parse(rawData).data.token;
        const options = {
          headers: {
            Authorization: 'Bearer ' + token,
            'Content-Type': 'application/json',
          },
        };
        const results = [];
        http
          .get(url, options, function (response) {
            console.log(response.statusCode);

            let rawData = '';
            response.on('data', (chunk) => {
              rawData += chunk;
            });

            response.on('end', () => {
              const parsedData = JSON.parse(rawData);
              console.log('');
              console.log('');
              function storeResults(x) {
                for (let i = 0; i < p; i++) {
                  results.push([
                    x[i].home_team_en,
                    x[i].home_score,
                    x[i].away_team_en,
                    x[i].away_score,
                  ]);
                }
                return results;
              }
              storeResults(parsedData.data);
              console.log('apple');
              results.forEach((result) => {
                console.log(result);
              });
            });
          })
          .on('error', (error) => {
            console.log(error);
          });
      });
    }
  );
  reqq.write(dataz);
  reqq.end();
}

const app = express();
app.set('view engine', 'ejs');
app.use('/public', express.static(path.join(__dirname, '/public')));

app.get('/', function (req, res) {
  const picks = [
    {
      sheet: 'Diego',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 0, 'Netherlands', 2],
        [2, 'England', 3, 'Iran', 0],
        [1, 'Qatar', 0, 'Ecuador', 2],
        [4, 'United States', 2, 'Wales', 1],
        [5, 'Argentina', 3, 'Saudi Arabia', 0],
        [6, 'Denmark', 2, 'Tunisia', 0],
        [7, 'Mexico', 2, 'Poland', 1],
        [8, 'France', 2, 'Australia', 0],
        [9, 'Morocco', 0, 'Croatia', 3],
        [10, 'Germany', 2, 'Japan', 1],
        [11, 'Spain', 2, 'Costa Rica', 1],
        [12, 'Belgium', 3, 'Canada', 0],
        [13, 'Switzerland', 2, 'Cameroon', 0],
        [14, 'Uruguay', 2, 'South Korea', 2],
        [15, 'Portugal', 3, 'Ghana', 0],
        [16, 'Brazil', 3, 'Serbia', 0],
        [17, 'Iran', 0, 'Wales', 2],
        [18, 'Qatar', 1, 'Senegal', 2],
        [19, 'Netherlands', 2, 'Ecuador', 1],
        [20, 'England', 1, 'United States', 1],
        [21, 'Tunisia', 0, 'Australia', 2],
        [22, 'Poland', 3, 'Saudi Arabia', 0],
        [23, 'France', 2, 'Denmark', 1],
        [24, 'Argentina', 1, 'Mexico', 1],
        [25, 'Japan', 3, 'Costa Rica', 1],
        [26, 'Belgium', 3, 'Morocco', 0],
        [27, 'Croatia', 2, 'Canada', 0],
        [28, 'Spain', 2, 'Germany', 2],
        [29, 'Serbia', 2, 'Cameroon', 1],
        [30, 'South Korea', 3, 'Ghana', 1],
        [31, 'Brazil', 2, 'Switzerland', 1],
        [32, 'Portugal', 2, 'Uruguay', 1],
        [33, 'Ecuador', 2, 'Senegal', 0],
        [34, 'Netherlands', 3, 'Qatar', 0],
        [35, 'Iran', 0, 'United States', 2],
        [36, 'England', 2, 'Wales', 1],
        [37, 'Denmark', 2, 'Australia', 2],
        [38, 'Tunisia', 0, 'France', 3],
        [39, 'Poland', 1, 'Argentina', 2],
        [40, 'Saudi Arabia', 0, 'Mexico', 3],
        [41, 'Canada', 1, 'Morocco', 0],
        [42, 'Croatia', 2, 'Belguim', 2],
        [43, 'Costa Rica', 0, 'Germany', 2],
        [44, 'Japan', 1, 'Spain', 3],
        [45, 'Ghana', 1, 'Uruguay', 3],
        [56, 'South Korea', 1, 'Portugal', 3],
        [47, 'Brazil', 3, 'Cameroon', 0],
        [48, 'Serbia', 1, 'Switzerland', 2],
      ],
      points: 0,
    },
    {
      sheet: 'David ',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 1],
        [2, 'England', 3, 'Iran', 0],
        [1, 'Qatar', 1, 'Ecuador', 2],
        [4, 'United States', 2, 'Wales', 1],
        [5, 'Argentina', 3, 'Saudi Arabia', 0],
        [6, 'Denmark', 2, 'Tunisia', 1],
        [7, 'Mexico', 1, 'Poland', 1],
        [8, 'France', 3, 'Australia', 1],
        [9, 'Morocco', 1, 'Croatia', 2],
        [10, 'Germany', 3, 'Japan', 2],
        [11, 'Spain', 3, 'Costa Rica', 0],
        [12, 'Belgium', 3, 'Canada', 1],
        [13, 'Switzerland', 2, 'Cameroon', 1],
        [14, 'Uruguay', 2, 'South Korea', 1],
        [15, 'Portugal', 1, 'Ghana', 0],
        [16, 'Brazil', 3, 'Serbia', 1],
        [17, 'Iran', 0, 'Wales', 2],
        [18, 'Qatar', 0, 'Senegal', 2],
        [19, 'Netherlands', 2, 'Ecuador', 2],
        [20, 'England', 2, 'United States', 1],
        [21, 'Tunisia', 2, 'Australia', 2],
        [22, 'Poland', 3, 'Saudi Arabia', 2],
        [23, 'France', 3, 'Denmark', 2],
        [24, 'Argentina', 3, 'Mexico', 1],
        [25, 'Japan', 2, 'Costa Rica', 0],
        [26, 'Belgium', 3, 'Morocco', 1],
        [27, 'Croatia', 2, 'Canada', 0],
        [28, 'Spain', 2, 'Germany', 1],
        [29, 'Serbia', 1, 'Cameroon', 0],
        [30, 'South Korea', 1, 'Ghana', 1],
        [31, 'Brazil', 3, 'Switzerland', 1],
        [32, 'Portugal', 2, 'Uruguay', 1],
        [33, 'Ecuador', 0, 'Senegal', 1],
        [34, 'Netherlands', 2, 'Qatar', 0],
        [35, 'Iran', 0, 'United States', 2],
        [36, 'England', 3, 'Wales', 1],
        [37, 'Denmark', 2, 'Australia', 0],
        [38, 'Tunisia', 0, 'France', 3],
        [39, 'Poland', 1, 'Argentina', 2],
        [40, 'Saudi Arabia', 2, 'Mexico', 2],
        [41, 'Canada', 0, 'Morocco', 1],
        [42, 'Croatia', 2, 'Belguim', 2],
        [43, 'Costa Rica', 0, 'Germany', 3],
        [44, 'Japan', 1, 'Spain', 2],
        [45, 'Ghana', 1, 'Uruguay', 2],
        [56, 'South Korea', 1, 'Portugal', 2],
        [47, 'Brazil', 3, 'Cameroon', 0],
        [48, 'Serbia', 1, 'Switzerland', 1],
      ],
      points: 0,
    },
    {
      sheet: 'Kiki ',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 2],
        [2, 'England', 2, 'Iran', 1],
        [1, 'Qatar', 0, 'Ecuador', 2],
        [4, 'United States', 1, 'Wales', 0],
        [5, 'Argentina', 3, 'Saudi Arabia', 0],
        [6, 'Denmark', 1, 'Tunisia', 0],
        [7, 'Mexico', 1, 'Poland', 0],
        [8, 'France', 2, 'Australia', 0],
        [9, 'Morocco', 0, 'Croatia', 1],
        [10, 'Germany', 2, 'Japan', 1],
        [11, 'Spain', 3, 'Costa Rica', 0],
        [12, 'Belgium', 2, 'Canada', 0],
        [13, 'Switzerland', 1, 'Cameroon', 0],
        [14, 'Uruguay', 2, 'South Korea', 1],
        [15, 'Portugal', 3, 'Ghana', 0],
        [16, 'Brazil', 3, 'Serbia', 1],
        [17, 'Iran', 0, 'Wales', 1],
        [18, 'Qatar', 0, 'Senegal', 1],
        [19, 'Netherlands', 3, 'Ecuador', 0],
        [20, 'England', 2, 'United States', 1],
        [21, 'Tunisia', 1, 'Australia', 1],
        [22, 'Poland', 1, 'Saudi Arabia', 0],
        [23, 'France', 3, 'Denmark', 2],
        [24, 'Argentina', 3, 'Mexico', 0],
        [25, 'Japan', 2, 'Costa Rica', 0],
        [26, 'Belgium', 2, 'Morocco', 0],
        [27, 'Croatia', 1, 'Canada', 0],
        [28, 'Spain', 0, 'Germany', 1],
        [29, 'Serbia', 1, 'Cameroon', 0],
        [30, 'South Korea', 2, 'Ghana', 0],
        [31, 'Brazil', 2, 'Switzerland', 0],
        [32, 'Portugal', 2, 'Uruguay', 1],
        [33, 'Ecuador', 0, 'Senegal', 1],
        [34, 'Netherlands', 2, 'Qatar', 0],
        [35, 'Iran', 0, 'United States', 1],
        [36, 'England', 2, 'Wales', 1],
        [37, 'Denmark', 1, 'Australia', 0],
        [38, 'Tunisia', 0, 'France', 2],
        [39, 'Poland', 1, 'Argentina', 3],
        [40, 'Saudi Arabia', 1, 'Mexico', 2],
        [41, 'Canada', 0, 'Morocco', 2],
        [42, 'Croatia', 0, 'Belguim', 1],
        [43, 'Costa Rica', 0, 'Germany', 2],
        [44, 'Japan', 1, 'Spain', 2],
        [45, 'Ghana', 0, 'Uruguay', 1],
        [56, 'South Korea', 1, 'Portugal', 3],
        [47, 'Brazil', 2, 'Cameroon', 0],
        [48, 'Serbia', 0, 'Switzerland', 0],
      ],
      points: 0,
    },
    {
      sheet: 'Jazz',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 2],
        [2, 'England', 3, 'Iran', 1],
        [1, 'Qatar', 0, 'Ecuador', 2],
        [4, 'United States', 1, 'Wales', 0],
        [5, 'Argentina', 3, 'Saudi Arabia', 0],
        [6, 'Denmark', 1, 'Tunisia', 0],
        [7, 'Mexico', 1, 'Poland', 0],
        [8, 'France', 3, 'Australia', 0],
        [9, 'Morocco', 0, 'Croatia', 1],
        [10, 'Germany', 2, 'Japan', 1],
        [11, 'Spain', 2, 'Costa Rica', 0],
        [12, 'Belgium', 3, 'Canada', 1],
        [13, 'Switzerland', 1, 'Cameroon', 0],
        [14, 'Uruguay', 2, 'South Korea', 1],
        [15, 'Portugal', 1, 'Ghana', 0],
        [16, 'Brazil', 3, 'Serbia', 0],
        [17, 'Iran', 0, 'Wales', 1],
        [18, 'Qatar', 0, 'Senegal', 1],
        [19, 'Netherlands', 2, 'Ecuador', 0],
        [20, 'England', 2, 'United States', 1],
        [21, 'Tunisia', 0, 'Australia', 0],
        [22, 'Poland', 1, 'Saudi Arabia', 0],
        [23, 'France', 3, 'Denmark', 1],
        [24, 'Argentina', 2, 'Mexico', 1],
        [25, 'Japan', 1, 'Costa Rica', 0],
        [26, 'Belgium', 2, 'Morocco', 0],
        [27, 'Croatia', 2, 'Canada', 0],
        [28, 'Spain', 1, 'Germany', 1],
        [29, 'Serbia', 2, 'Cameroon', 0],
        [30, 'South Korea', 2, 'Ghana', 0],
        [31, 'Brazil', 3, 'Switzerland', 0],
        [32, 'Portugal', 1, 'Uruguay', 0],
        [33, 'Ecuador', 1, 'Senegal', 1],
        [34, 'Netherlands', 3, 'Qatar', 0],
        [35, 'Iran', 0, 'United States', 2],
        [36, 'England', 2, 'Wales', 1],
        [37, 'Denmark', 1, 'Australia', 0],
        [38, 'Tunisia', 0, 'France', 3],
        [39, 'Poland', 1, 'Argentina', 2],
        [40, 'Saudi Arabia', 1, 'Mexico', 2],
        [41, 'Canada', 1, 'Morocco', 1],
        [42, 'Croatia', 1, 'Belguim', 2],
        [43, 'Costa Rica', 0, 'Germany', 2],
        [44, 'Japan', 1, 'Spain', 2],
        [45, 'Ghana', 0, 'Uruguay', 1],
        [56, 'South Korea', 0, 'Portugal', 2],
        [47, 'Brazil', 2, 'Cameroon', 0],
        [48, 'Serbia', 0, 'Switzerland', 0],
      ],
      points: 0,
    },
    {
      sheet: 'David III',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 2],
        [2, 'England', 3, 'Iran', 0],
        [1, 'Qatar', 1, 'Ecuador', 2],
        [4, 'United States', 1, 'Wales', 1],
        [5, 'Argentina', 2, 'Saudi Arabia', 0],
        [6, 'Denmark', 1, 'Tunisia', 0],
        [7, 'Mexico', 1, 'Poland', 2],
        [8, 'France', 3, 'Australia', 0],
        [9, 'Morocco', 1, 'Croatia', 1],
        [10, 'Germany', 2, 'Japan', 0],
        [11, 'Spain', 2, 'Costa Rica', 0],
        [12, 'Belgium', 3, 'Canada', 1],
        [13, 'Switzerland', 1, 'Cameroon', 0],
        [14, 'Uruguay', 2, 'South Korea', 1],
        [15, 'Portugal', 2, 'Ghana', 0],
        [16, 'Brazil', 3, 'Serbia', 1],
        [17, 'Iran', 0, 'Wales', 1],
        [18, 'Qatar', 0, 'Senegal', 2],
        [19, 'Netherlands', 2, 'Ecuador', 0],
        [20, 'England', 3, 'United States', 1],
        [21, 'Tunisia', 2, 'Australia', 2],
        [22, 'Poland', 2, 'Saudi Arabia', 1],
        [23, 'France', 3, 'Denmark', 1],
        [24, 'Argentina', 3, 'Mexico', 1],
        [25, 'Japan', 2, 'Costa Rica', 1],
        [26, 'Belgium', 3, 'Morocco', 0],
        [27, 'Croatia', 1, 'Canada', 1],
        [28, 'Spain', 1, 'Germany', 2],
        [29, 'Serbia', 1, 'Cameroon', 0],
        [30, 'South Korea', 1, 'Ghana', 0],
        [31, 'Brazil', 3, 'Switzerland', 1],
        [32, 'Portugal', 2, 'Uruguay', 1],
        [33, 'Ecuador', 0, 'Senegal', 1],
        [34, 'Netherlands', 2, 'Qatar', 0],
        [35, 'Iran', 0, 'United States', 2],
        [36, 'England', 2, 'Wales', 0],
        [37, 'Denmark', 1, 'Australia', 0],
        [38, 'Tunisia', 0, 'France', 2],
        [39, 'Poland', 1, 'Argentina', 2],
        [40, 'Saudi Arabia', 1, 'Mexico', 2],
        [41, 'Canada', 1, 'Morocco', 0],
        [42, 'Croatia', 1, 'Belguim', 3],
        [43, 'Costa Rica', 0, 'Germany', 2],
        [44, 'Japan', 0, 'Spain', 2],
        [45, 'Ghana', 0, 'Uruguay', 1],
        [56, 'South Korea', 1, 'Portugal', 2],
        [47, 'Brazil', 3, 'Cameroon', 1],
        [48, 'Serbia', 0, 'Switzerland', 0],
      ],
      points: 0,
    },
    {
      sheet: 'Gal',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 2],
        [2, 'England', 3, 'Iran', 0],
        [1, 'Qatar', 0, 'Ecuador', 1],
        [4, 'United States', 2, 'Wales', 1],
        [5, 'Argentina', 3, 'Saudi Arabia', 0],
        [6, 'Denmark', 2, 'Tunisia', 1],
        [7, 'Mexico', 3, 'Poland', 1],
        [8, 'France', 3, 'Australia', 0],
        [9, 'Morocco', 0, 'Croatia', 2],
        [10, 'Germany', 3, 'Japan', 2],
        [11, 'Spain', 4, 'Costa Rica', 1],
        [12, 'Belgium', 2, 'Canada', 0],
        [13, 'Switzerland', 2, 'Cameroon', 0],
        [14, 'Uruguay', 2, 'South Korea', 2],
        [15, 'Portugal', 2, 'Ghana', 1],
        [16, 'Brazil', 3, 'Serbia', 0],
        [17, 'Iran', 1, 'Wales', 1],
        [18, 'Qatar', 2, 'Senegal', 2],
        [19, 'Netherlands', 2, 'Ecuador', 0],
        [20, 'England', 3, 'United States', 1],
        [21, 'Tunisia', 0, 'Australia', 1],
        [22, 'Poland', 1, 'Saudi Arabia', 0],
        [23, 'France', 2, 'Denmark', 1],
        [24, 'Argentina', 2, 'Mexico', 0],
        [25, 'Japan', 2, 'Costa Rica', 1],
        [26, 'Belgium', 3, 'Morocco', 0],
        [27, 'Croatia', 2, 'Canada', 1],
        [28, 'Spain', 2, 'Germany', 1],
        [29, 'Serbia', 2, 'Cameroon', 1],
        [30, 'South Korea', 2, 'Ghana', 1],
        [31, 'Brazil', 3, 'Switzerland', 1],
        [32, 'Portugal', 1, 'Uruguay', 2],
        [33, 'Ecuador', 1, 'Senegal', 0],
        [34, 'Netherlands', 2, 'Qatar', 0],
        [35, 'Iran', 0, 'United States', 2],
        [36, 'England', 2, 'Wales', 0],
        [37, 'Denmark', 2, 'Australia', 1],
        [38, 'Tunisia', 0, 'France', 2],
        [39, 'Poland', 0, 'Argentina', 2],
        [40, 'Saudi Arabia', 1, 'Mexico', 2],
        [41, 'Canada', 2, 'Morocco', 0],
        [42, 'Croatia', 2, 'Belguim', 2],
        [43, 'Costa Rica', 0, 'Germany', 4],
        [44, 'Japan', 1, 'Spain', 2],
        [45, 'Ghana', 1, 'Uruguay', 2],
        [56, 'South Korea', 0, 'Portugal', 2],
        [47, 'Brazil', 3, 'Cameroon', 1],
        [48, 'Serbia', 0, 'Switzerland', 2],
      ],
      points: 0,
    },
    {
      sheet: 'Damian',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 2],
        [2, 'England', 3, 'Iran', 0],
        [1, 'Qatar', 0, 'Ecuador', 2],
        [4, 'United States', 1, 'Wales', 1],
        [5, 'Argentina', 3, 'Saudi Arabia', 0],
        [6, 'Denmark', 2, 'Tunisia', 0],
        [7, 'Mexico', 2, 'Poland', 1],
        [8, 'France', 3, 'Australia', 1],
        [9, 'Morocco', 0, 'Croatia', 1],
        [10, 'Germany', 2, 'Japan', 1],
        [11, 'Spain', 2, 'Costa Rica', 0],
        [12, 'Belgium', 3, 'Canada', 2],
        [13, 'Switzerland', 1, 'Cameroon', 2],
        [14, 'Uruguay', 1, 'South Korea', 0],
        [15, 'Portugal', 2, 'Ghana', 0],
        [16, 'Brazil', 3, 'Serbia', 0],
        [17, 'Iran', 1, 'Wales', 2],
        [18, 'Qatar', 1, 'Senegal', 2],
        [19, 'Netherlands', 3, 'Ecuador', 2],
        [20, 'England', 2, 'United States', 0],
        [21, 'Tunisia', 1, 'Australia', 2],
        [22, 'Poland', 2, 'Saudi Arabia', 0],
        [23, 'France', 1, 'Denmark', 1],
        [24, 'Argentina', 3, 'Mexico', 1],
        [25, 'Japan', 2, 'Costa Rica', 1],
        [26, 'Belgium', 3, 'Morocco', 1],
        [27, 'Croatia', 2, 'Canada', 2],
        [28, 'Spain', 3, 'Germany', 3],
        [29, 'Serbia', 1, 'Cameroon', 1],
        [30, 'South Korea', 2, 'Ghana', 1],
        [31, 'Brazil', 3, 'Switzerland', 0],
        [32, 'Portugal', 3, 'Uruguay', 1],
        [33, 'Ecuador', 1, 'Senegal', 1],
        [34, 'Netherlands', 2, 'Qatar', 0],
        [35, 'Iran', 0, 'United States', 2],
        [36, 'England', 2, 'Wales', 1],
        [37, 'Denmark', 1, 'Australia', 0],
        [38, 'Tunisia', 1, 'France', 4],
        [39, 'Poland', 1, 'Argentina', 3],
        [40, 'Saudi Arabia', 0, 'Mexico', 2],
        [41, 'Canada', 1, 'Morocco', 1],
        [42, 'Croatia', 1, 'Belguim', 2],
        [43, 'Costa Rica', 0, 'Germany', 2],
        [44, 'Japan', 1, 'Spain', 2],
        [45, 'Ghana', 2, 'Uruguay', 2],
        [56, 'South Korea', 1, 'Portugal', 3],
        [47, 'Brazil', 2, 'Cameroon', 0],
        [48, 'Serbia', 2, 'Switzerland', 2],
      ],
      points: 0,
    },
    {
      sheet: 'Chupas',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 2],
        [2, 'England', 3, 'Iran', 0],
        [1, 'Qatar', 1, 'Ecuador', 3],
        [4, 'United States', 0, 'Wales', 1],
        [5, 'Argentina', 4, 'Saudi Arabia', 0],
        [6, 'Denmark', 2, 'Tunisia', 0],
        [7, 'Mexico', 1, 'Poland', 0],
        [8, 'France', 3, 'Australia', 1],
        [9, 'Morocco', 1, 'Croatia', 3],
        [10, 'Germany', 3, 'Japan', 0],
        [11, 'Spain', 2, 'Costa Rica', 0],
        [12, 'Belgium', 2, 'Canada', 1],
        [13, 'Switzerland', 2, 'Cameroon', 1],
        [14, 'Uruguay', 3, 'South Korea', 1],
        [15, 'Portugal', 1, 'Ghana', 0],
        [16, 'Brazil', 3, 'Serbia', 0],
        [17, 'Iran', 1, 'Wales', 2],
        [18, 'Qatar', 1, 'Senegal', 0],
        [19, 'Netherlands', 2, 'Ecuador', 1],
        [20, 'England', 1, 'United States', 0],
        [21, 'Tunisia', 1, 'Australia', 2],
        [22, 'Poland', 2, 'Saudi Arabia', 0],
        [23, 'France', 3, 'Denmark', 1],
        [24, 'Argentina', 3, 'Mexico', 2],
        [25, 'Japan', 0, 'Costa Rica', 2],
        [26, 'Belgium', 4, 'Morocco', 0],
        [27, 'Croatia', 3, 'Canada', 1],
        [28, 'Spain', 2, 'Germany', 1],
        [29, 'Serbia', 0, 'Cameroon', 1],
        [30, 'South Korea', 1, 'Ghana', 0],
        [31, 'Brazil', 2, 'Switzerland', 0],
        [32, 'Portugal', 1, 'Uruguay', 2],
        [33, 'Ecuador', 3, 'Senegal', 1],
        [34, 'Netherlands', 2, 'Qatar', 0],
        [35, 'Iran', 1, 'United States', 2],
        [36, 'England', 2, 'Wales', 1],
        [37, 'Denmark', 0, 'Australia', 2],
        [38, 'Tunisia', 0, 'France', 4],
        [39, 'Poland', 1, 'Argentina', 3],
        [40, 'Saudi Arabia', 0, 'Mexico', 2],
        [41, 'Canada', 2, 'Morocco', 0],
        [42, 'Croatia', 2, 'Belguim', 3],
        [43, 'Costa Rica', 1, 'Germany', 3],
        [44, 'Japan', 0, 'Spain', 3],
        [45, 'Ghana', 1, 'Uruguay', 2],
        [56, 'South Korea', 0, 'Portugal', 2],
        [47, 'Brazil', 3, 'Cameroon', 1],
        [48, 'Serbia', 1, 'Switzerland', 2],
      ],
      points: 0,
    },
    {
      sheet: 'Clyde',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 0, 'Netherlands', 2],
        [2, 'England', 3, 'Iran', 1],
        [1, 'Qatar', 1, 'Ecuador', 1],
        [4, 'United States', 2, 'Wales', 1],
        [5, 'Argentina', 3, 'Saudi Arabia', 0],
        [6, 'Denmark', 2, 'Tunisia', 0],
        [7, 'Mexico', 2, 'Poland', 1],
        [8, 'France', 3, 'Australia', 1],
        [9, 'Morocco', 0, 'Croatia', 2],
        [10, 'Germany', 3, 'Japan', 1],
        [11, 'Spain', 3, 'Costa Rica', 1],
        [12, 'Belgium', 3, 'Canada', 1],
        [13, 'Switzerland', 2, 'Cameroon', 2],
        [14, 'Uruguay', 3, 'South Korea', 1],
        [15, 'Portugal', 2, 'Ghana', 1],
        [16, 'Brazil', 3, 'Serbia', 0],
        [17, 'Iran', 1, 'Wales', 1],
        [18, 'Qatar', 1, 'Senegal', 0],
        [19, 'Netherlands', 2, 'Ecuador', 1],
        [20, 'England', 2, 'United States', 0],
        [21, 'Tunisia', 1, 'Australia', 1],
        [22, 'Poland', 2, 'Saudi Arabia', 0],
        [23, 'France', 2, 'Denmark', 1],
        [24, 'Argentina', 2, 'Mexico', 1],
        [25, 'Japan', 2, 'Costa Rica', 2],
        [26, 'Belgium', 2, 'Morocco', 1],
        [27, 'Croatia', 2, 'Canada', 1],
        [28, 'Spain', 1, 'Germany', 2],
        [29, 'Serbia', 1, 'Cameroon', 1],
        [30, 'South Korea', 1, 'Ghana', 0],
        [31, 'Brazil', 2, 'Switzerland', 1],
        [32, 'Portugal', 1, 'Uruguay', 1],
        [33, 'Ecuador', 2, 'Senegal', 1],
        [34, 'Netherlands', 2, 'Qatar', 0],
        [35, 'Iran', 0, 'United States', 2],
        [36, 'England', 2, 'Wales', 0],
        [37, 'Denmark', 2, 'Australia', 0],
        [38, 'Tunisia', 0, 'France', 3],
        [39, 'Poland', 1, 'Argentina', 2],
        [40, 'Saudi Arabia', 1, 'Mexico', 2],
        [41, 'Canada', 1, 'Morocco', 0],
        [42, 'Croatia', 2, 'Belguim', 2],
        [43, 'Costa Rica', 0, 'Germany', 3],
        [44, 'Japan', 1, 'Spain', 2],
        [45, 'Ghana', 1, 'Uruguay', 2],
        [56, 'South Korea', 1, 'Portugal', 2],
        [47, 'Brazil', 2, 'Cameroon', 0],
        [48, 'Serbia', 1, 'Switzerland', 1],
      ],
      points: 0,
    },
    {
      sheet: 'Eddie',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 0, 'Netherlands', 3],
        [2, 'England', 2, 'Iran', 0],
        [1, 'Qatar', 1, 'Ecuador', 3],
        [4, 'United States', 2, 'Wales', 0],
        [5, 'Argentina', 4, 'Saudi Arabia', 0],
        [6, 'Denmark', 3, 'Tunisia', 1],
        [7, 'Mexico', 2, 'Poland', 1],
        [8, 'France', 3, 'Australia', 0],
        [9, 'Morocco', 1, 'Croatia', 3],
        [10, 'Germany', 3, 'Japan', 2],
        [11, 'Spain', 2, 'Costa Rica', 2],
        [12, 'Belgium', 3, 'Canada', 2],
        [13, 'Switzerland', 1, 'Cameroon', 1],
        [14, 'Uruguay', 3, 'South Korea', 1],
        [15, 'Portugal', 3, 'Ghana', 0],
        [16, 'Brazil', 4, 'Serbia', 1],
        [17, 'Iran', 2, 'Wales', 2],
        [18, 'Qatar', 3, 'Senegal', 2],
        [19, 'Netherlands', 2, 'Ecuador', 1],
        [20, 'England', 1, 'United States', 1],
        [21, 'Tunisia', 1, 'Australia', 2],
        [22, 'Poland', 2, 'Saudi Arabia', 0],
        [23, 'France', 3, 'Denmark', 2],
        [24, 'Argentina', 3, 'Mexico', 2],
        [25, 'Japan', 3, 'Costa Rica', 2],
        [26, 'Belgium', 2, 'Morocco', 0],
        [27, 'Croatia', 2, 'Canada', 1],
        [28, 'Spain', 2, 'Germany', 3],
        [29, 'Serbia', 1, 'Cameroon', 1],
        [30, 'South Korea', 1, 'Ghana', 0],
        [31, 'Brazil', 3, 'Switzerland', 1],
        [32, 'Portugal', 2, 'Uruguay', 2],
        [33, 'Ecuador', 2, 'Senegal', 1],
        [34, 'Netherlands', 3, 'Qatar', 1],
        [35, 'Iran', 1, 'United States', 3],
        [36, 'England', 2, 'Wales', 1],
        [37, 'Denmark', 2, 'Australia', 0],
        [38, 'Tunisia', 0, 'France', 3],
        [39, 'Poland', 2, 'Argentina', 4],
        [40, 'Saudi Arabia', 1, 'Mexico', 3],
        [41, 'Canada', 2, 'Morocco', 0],
        [42, 'Croatia', 2, 'Belguim', 3],
        [43, 'Costa Rica', 1, 'Germany', 3],
        [44, 'Japan', 2, 'Spain', 2],
        [45, 'Ghana', 0, 'Uruguay', 3],
        [56, 'South Korea', 1, 'Portugal', 2],
        [47, 'Brazil', 3, 'Cameroon', 0],
        [48, 'Serbia', 1, 'Switzerland', 1],
      ],
      points: 0,
    },
    {
      sheet: 'Kat',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 3, 'Netherlands', 1],
        [2, 'England', 2, 'Iran', 0],
        [1, 'Qatar', 0, 'Ecuador', 3],
        [4, 'United States', 2, 'Wales', 1],
        [5, 'Argentina', 4, 'Saudi Arabia', 0],
        [6, 'Denmark', 2, 'Tunisia', 0],
        [7, 'Mexico', 1, 'Poland', 0],
        [8, 'France', 1, 'Australia', 0],
        [9, 'Morocco', 1, 'Croatia', 3],
        [10, 'Germany', 3, 'Japan', 2],
        [11, 'Spain', 3, 'Costa Rica', 0],
        [12, 'Belgium', 2, 'Canada', 1],
        [13, 'Switzerland', 1, 'Cameroon', 0],
        [14, 'Uruguay', 1, 'South Korea', 2],
        [15, 'Portugal', 3, 'Ghana', 0],
        [16, 'Brazil', 4, 'Serbia', 0],
        [17, 'Iran', 1, 'Wales', 2],
        [18, 'Qatar', 1, 'Senegal', 3],
        [19, 'Netherlands', 2, 'Ecuador', 0],
        [20, 'England', 3, 'United States', 2],
        [21, 'Tunisia', 1, 'Australia', 1],
        [22, 'Poland', 2, 'Saudi Arabia', 1],
        [23, 'France', 1, 'Denmark', 2],
        [24, 'Argentina', 2, 'Mexico', 0],
        [25, 'Japan', 2, 'Costa Rica', 0],
        [26, 'Belgium', 4, 'Morocco', 1],
        [27, 'Croatia', 3, 'Canada', 1],
        [28, 'Spain', 3, 'Germany', 2],
        [29, 'Serbia', 3, 'Cameroon', 1],
        [30, 'South Korea', 4, 'Ghana', 0],
        [31, 'Brazil', 3, 'Switzerland', 0],
        [32, 'Portugal', 2, 'Uruguay', 1],
        [33, 'Ecuador', 3, 'Senegal', 0],
        [34, 'Netherlands', 2, 'Qatar', 0],
        [35, 'Iran', 1, 'United States', 4],
        [36, 'England', 3, 'Wales', 1],
        [37, 'Denmark', 2, 'Australia', 0],
        [38, 'Tunisia', 0, 'France', 3],
        [39, 'Poland', 0, 'Argentina', 2],
        [40, 'Saudi Arabia', 1, 'Mexico', 3],
        [41, 'Canada', 3, 'Morocco', 3],
        [42, 'Croatia', 1, 'Belguim', 2],
        [43, 'Costa Rica', 1, 'Germany', 2],
        [44, 'Japan', 1, 'Spain', 2],
        [45, 'Ghana', 2, 'Uruguay', 4],
        [56, 'South Korea', 1, 'Portugal', 2],
        [47, 'Brazil', 3, 'Cameroon', 1],
        [48, 'Serbia', 2, 'Switzerland', 2],
      ],
      points: 0,
    },
    {
      sheet: 'Alex',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 2, 'Netherlands', 1],
        [2, 'England', 2, 'Iran', 0],
        [1, 'Qatar', 0, 'Ecuador', 2],
        [4, 'United States', 2, 'Wales', 1],
        [5, 'Argentina', 3, 'Saudi Arabia', 0],
        [6, 'Denmark', 3, 'Tunisia', 0],
        [7, 'Mexico', 1, 'Poland', 1],
        [8, 'France', 3, 'Australia', 1],
        [9, 'Morocco', 1, 'Croatia', 3],
        [10, 'Germany', 2, 'Japan', 1],
        [11, 'Spain', 2, 'Costa Rica', 0],
        [12, 'Belgium', 2, 'Canada', 2],
        [13, 'Switzerland', 1, 'Cameroon', 0],
        [14, 'Uruguay', 2, 'South Korea', 1],
        [15, 'Portugal', 3, 'Ghana', 1],
        [16, 'Brazil', 4, 'Serbia', 0],
        [17, 'Iran', 1, 'Wales', 0],
        [18, 'Qatar', 1, 'Senegal', 3],
        [19, 'Netherlands', 2, 'Ecuador', 0],
        [20, 'England', 3, 'United States', 1],
        [21, 'Tunisia', 0, 'Australia', 1],
        [22, 'Poland', 3, 'Saudi Arabia', 1],
        [23, 'France', 1, 'Denmark', 1],
        [24, 'Argentina', 3, 'Mexico', 1],
        [25, 'Japan', 2, 'Costa Rica', 2],
        [26, 'Belgium', 3, 'Morocco', 1],
        [27, 'Croatia', 3, 'Canada', 2],
        [28, 'Spain', 1, 'Germany', 1],
        [29, 'Serbia', 2, 'Cameroon', 1],
        [30, 'South Korea', 2, 'Ghana', 0],
        [31, 'Brazil', 2, 'Switzerland', 0],
        [32, 'Portugal', 1, 'Uruguay', 2],
        [33, 'Ecuador', 0, 'Senegal', 2],
        [34, 'Netherlands', 4, 'Qatar', 1],
        [35, 'Iran', 0, 'United States', 3],
        [36, 'England', 2, 'Wales', 0],
        [37, 'Denmark', 2, 'Australia', 1],
        [38, 'Tunisia', 0, 'France', 4],
        [39, 'Poland', 1, 'Argentina', 2],
        [40, 'Saudi Arabia', 0, 'Mexico', 3],
        [41, 'Canada', 5, 'Morocco', 0],
        [42, 'Croatia', 2, 'Belguim', 2],
        [43, 'Costa Rica', 0, 'Germany', 3],
        [44, 'Japan', 1, 'Spain', 2],
        [45, 'Ghana', 2, 'Uruguay', 4],
        [56, 'South Korea', 2, 'Portugal', 1],
        [47, 'Brazil', 3, 'Cameroon', 1],
        [48, 'Serbia', 0, 'Switzerland', 2],
      ],
      points: 0,
    },
    {
      sheet: 'Chris',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 2],
        [2, 'England', 2, 'Iran', 0],
        [1, 'Qatar', 1, 'Ecuador', 1],
        [4, 'United States', 1, 'Wales', 0],
        [5, 'Argentina', 3, 'Saudi Arabia', 0],
        [6, 'Denmark', 2, 'Tunisia', 0],
        [7, 'Mexico', 0, 'Poland', 1],
        [8, 'France', 2, 'Australia', 0],
        [9, 'Morocco', 2, 'Croatia', 2],
        [10, 'Germany', 2, 'Japan', 0],
        [11, 'Spain', 2, 'Costa Rica', 0],
        [12, 'Belgium', 2, 'Canada', 1],
        [13, 'Switzerland', 2, 'Cameroon', 2],
        [14, 'Uruguay', 1, 'South Korea', 0],
        [15, 'Portugal', 1, 'Ghana', 1],
        [16, 'Brazil', 2, 'Serbia', 0],
        [17, 'Iran', 0, 'Wales', 1],
        [18, 'Qatar', 0, 'Senegal', 2],
        [19, 'Netherlands', 2, 'Ecuador', 1],
        [20, 'England', 2, 'United States', 1],
        [21, 'Tunisia', 1, 'Australia', 1],
        [22, 'Poland', 2, 'Saudi Arabia', 0],
        [23, 'France', 2, 'Denmark', 1],
        [24, 'Argentina', 2, 'Mexico', 1],
        [25, 'Japan', 1, 'Costa Rica', 0],
        [26, 'Belgium', 2, 'Morocco', 0],
        [27, 'Croatia', 1, 'Canada', 1],
        [28, 'Spain', 3, 'Germany', 2],
        [29, 'Serbia', 1, 'Cameroon', 0],
        [30, 'South Korea', 2, 'Ghana', 2],
        [31, 'Brazil', 2, 'Switzerland', 0],
        [32, 'Portugal', 0, 'Uruguay', 2],
        [33, 'Ecuador', 1, 'Senegal', 2],
        [34, 'Netherlands', 3, 'Qatar', 0],
        [35, 'Iran', 0, 'United States', 2],
        [36, 'England', 1, 'Wales', 1],
        [37, 'Denmark', 3, 'Australia', 1],
        [38, 'Tunisia', 1, 'France', 2],
        [39, 'Poland', 0, 'Argentina', 2],
        [40, 'Saudi Arabia', 1, 'Mexico', 1],
        [41, 'Canada', 1, 'Morocco', 3],
        [42, 'Croatia', 1, 'Belguim', 1],
        [43, 'Costa Rica', 0, 'Germany', 3],
        [44, 'Japan', 0, 'Spain', 2],
        [45, 'Ghana', 1, 'Uruguay', 1],
        [56, 'South Korea', 0, 'Portugal', 1],
        [47, 'Brazil', 1, 'Cameroon', 0],
        [48, 'Serbia', 2, 'Switzerland', 1],
      ],
      points: 0,
    },
    {
      sheet: 'Pepe',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 4],
        [2, 'England', 3, 'Iran', 1],
        [1, 'Qatar', 1, 'Ecuador', 2],
        [4, 'United States', 2, 'Wales', 2],
        [5, 'Argentina', 2, 'Saudi Arabia', 0],
        [6, 'Denmark', 1, 'Tunisia', 1],
        [7, 'Mexico', 2, 'Poland', 1],
        [8, 'France', 2, 'Australia', 0],
        [9, 'Morocco', 1, 'Croatia', 2],
        [10, 'Germany', 3, 'Japan', 1],
        [11, 'Spain', 2, 'Costa Rica', 0],
        [12, 'Belgium', 3, 'Canada', 0],
        [13, 'Switzerland', 1, 'Cameroon', 0],
        [14, 'Uruguay', 1, 'South Korea', 2],
        [15, 'Portugal', 4, 'Ghana', 1],
        [16, 'Brazil', 4, 'Serbia', 0],
        [17, 'Iran', 1, 'Wales', 1],
        [18, 'Qatar', 1, 'Senegal', 3],
        [19, 'Netherlands', 2, 'Ecuador', 0],
        [20, 'England', 1, 'United States', 1],
        [21, 'Tunisia', 0, 'Australia', 0],
        [22, 'Poland', 2, 'Saudi Arabia', 0],
        [23, 'France', 3, 'Denmark', 2],
        [24, 'Argentina', 3, 'Mexico', 1],
        [25, 'Japan', 0, 'Costa Rica', 1],
        [26, 'Belgium', 5, 'Morocco', 0],
        [27, 'Croatia', 3, 'Canada', 1],
        [28, 'Spain', 3, 'Germany', 3],
        [29, 'Serbia', 1, 'Cameroon', 0],
        [30, 'South Korea', 1, 'Ghana', 0],
        [31, 'Brazil', 3, 'Switzerland', 1],
        [32, 'Portugal', 3, 'Uruguay', 2],
        [33, 'Ecuador', 1, 'Senegal', 1],
        [34, 'Netherlands', 3, 'Qatar', 1],
        [35, 'Iran', 1, 'United States', 2],
        [36, 'England', 2, 'Wales', 1],
        [37, 'Denmark', 1, 'Australia', 0],
        [38, 'Tunisia', 2, 'France', 3],
        [39, 'Poland', 1, 'Argentina', 4],
        [40, 'Saudi Arabia', 0, 'Mexico', 1],
        [41, 'Canada', 1, 'Morocco', 1],
        [42, 'Croatia', 2, 'Belguim', 3],
        [43, 'Costa Rica', 0, 'Germany', 3],
        [44, 'Japan', 1, 'Spain', 2],
        [45, 'Ghana', 0, 'Uruguay', 2],
        [56, 'South Korea', 1, 'Portugal', 3],
        [47, 'Brazil', 4, 'Cameroon', 0],
        [48, 'Serbia', 2, 'Switzerland', 2],
      ],
      points: 0,
    },
    {
      sheet: 'Gio',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 3],
        [2, 'England', 2, 'Iran', 0],
        [1, 'Qatar', 1, 'Ecuador', 2],
        [4, 'United States', 2, 'Wales', 2],
        [5, 'Argentina', 3, 'Saudi Arabia', 0],
        [6, 'Denmark', 3, 'Tunisia', 1],
        [7, 'Mexico', 2, 'Poland', 1],
        [8, 'France', 4, 'Australia', 0],
        [9, 'Morocco', 1, 'Croatia', 5],
        [10, 'Germany', 2, 'Japan', 0],
        [11, 'Spain', 3, 'Costa Rica', 2],
        [12, 'Belgium', 1, 'Canada', 0],
        [13, 'Switzerland', 1, 'Cameroon', 1],
        [14, 'Uruguay', 3, 'South Korea', 1],
        [15, 'Portugal', 4, 'Ghana', 1],
        [16, 'Brazil', 3, 'Serbia', 0],
        [17, 'Iran', 0, 'Wales', 1],
        [18, 'Qatar', 0, 'Senegal', 2],
        [19, 'Netherlands', 3, 'Ecuador', 0],
        [20, 'England', 2, 'United States', 0],
        [21, 'Tunisia', 0, 'Australia', 0],
        [22, 'Poland', 2, 'Saudi Arabia', 0],
        [23, 'France', 3, 'Denmark', 1],
        [24, 'Argentina', 3, 'Mexico', 1],
        [25, 'Japan', 2, 'Costa Rica', 1],
        [26, 'Belgium', 4, 'Morocco', 0],
        [27, 'Croatia', 2, 'Canada', 1],
        [28, 'Spain', 2, 'Germany', 2],
        [29, 'Serbia', 2, 'Cameroon', 1],
        [30, 'South Korea', 4, 'Ghana', 1],
        [31, 'Brazil', 3, 'Switzerland', 0],
        [32, 'Portugal', 1, 'Uruguay', 1],
        [33, 'Ecuador', 2, 'Senegal', 3],
        [34, 'Netherlands', 3, 'Qatar', 0],
        [35, 'Iran', 0, 'United States', 3],
        [36, 'England', 2, 'Wales', 1],
        [37, 'Denmark', 1, 'Australia', 1],
        [38, 'Tunisia', 0, 'France', 6],
        [39, 'Poland', 2, 'Argentina', 2],
        [40, 'Saudi Arabia', 0, 'Mexico', 3],
        [41, 'Canada', 3, 'Morocco', 0],
        [42, 'Croatia', 3, 'Belguim', 3],
        [43, 'Costa Rica', 0, 'Germany', 2],
        [44, 'Japan', 1, 'Spain', 3],
        [45, 'Ghana', 0, 'Uruguay', 4],
        [56, 'South Korea', 0, 'Portugal', 3],
        [47, 'Brazil', 5, 'Cameroon', 1],
        [48, 'Serbia', 1, 'Switzerland', 2],
      ],
      points: 0,
    },
    {
      sheet: 'Tony',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 0, 'Netherlands', 2],
        [2, 'England', 2, 'Iran', 1],
        [1, 'Qatar', 2, 'Ecuador', 1],
        [4, 'United States', 1, 'Wales', 2],
        [5, 'Argentina', 2, 'Saudi Arabia', 0],
        [6, 'Denmark', 2, 'Tunisia', 0],
        [7, 'Mexico', 2, 'Poland', 1],
        [8, 'France', 2, 'Australia', 0],
        [9, 'Morocco', 0, 'Croatia', 2],
        [10, 'Germany', 2, 'Japan', 1],
        [11, 'Spain', 2, 'Costa Rica', 0],
        [12, 'Belgium', 2, 'Canada', 1],
        [13, 'Switzerland', 2, 'Cameroon', 1],
        [14, 'Uruguay', 2, 'South Korea', 1],
        [15, 'Portugal', 2, 'Ghana', 0],
        [16, 'Brazil', 2, 'Serbia', 0],
        [17, 'Iran', 0, 'Wales', 2],
        [18, 'Qatar', 2, 'Senegal', 1],
        [19, 'Netherlands', 2, 'Ecuador', 0],
        [20, 'England', 2, 'United States', 1],
        [21, 'Tunisia', 2, 'Australia', 2],
        [22, 'Poland', 2, 'Saudi Arabia', 1],
        [23, 'France', 2, 'Denmark', 1],
        [24, 'Argentina', 2, 'Mexico', 1],
        [25, 'Japan', 2, 'Costa Rica', 1],
        [26, 'Belgium', 2, 'Morocco', 1],
        [27, 'Croatia', 2, 'Canada', 1],
        [28, 'Spain', 1, 'Germany', 2],
        [29, 'Serbia', 2, 'Cameroon', 1],
        [30, 'South Korea', 2, 'Ghana', 1],
        [31, 'Brazil', 2, 'Switzerland', 0],
        [32, 'Portugal', 2, 'Uruguay', 1],
        [33, 'Ecuador', 1, 'Senegal', 2],
        [34, 'Netherlands', 2, 'Qatar', 1],
        [35, 'Iran', 1, 'United States', 2],
        [36, 'England', 2, 'Wales', 1],
        [37, 'Denmark', 2, 'Australia', 1],
        [38, 'Tunisia', 1, 'France', 2],
        [39, 'Poland', 1, 'Argentina', 2],
        [40, 'Saudi Arabia', 1, 'Mexico', 2],
        [41, 'Canada', 2, 'Morocco', 1],
        [42, 'Croatia', 1, 'Belguim', 2],
        [43, 'Costa Rica', 0, 'Germany', 2],
        [44, 'Japan', 0, 'Spain', 2],
        [45, 'Ghana', 0, 'Uruguay', 2],
        [56, 'South Korea', 0, 'Portugal', 2],
        [47, 'Brazil', 2, 'Cameroon', 0],
        [48, 'Serbia', 2, 'Switzerland', 1],
      ],
      points: 0,
    },
    {
      sheet: 'Sergio',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 2],
        [2, 'England', 2, 'Iran', 2],
        [1, 'Qatar', 0, 'Ecuador', 1],
        [4, 'United States', 1, 'Wales', 0],
        [5, 'Argentina', 3, 'Saudi Arabia', 1],
        [6, 'Denmark', 2, 'Tunisia', 0],
        [7, 'Mexico', 1, 'Poland', 1],
        [8, 'France', 2, 'Australia', 0],
        [9, 'Morocco', 0, 'Croatia', 1],
        [10, 'Germany', 1, 'Japan', 0],
        [11, 'Spain', 3, 'Costa Rica', 0],
        [12, 'Belgium', 2, 'Canada', 0],
        [13, 'Switzerland', 1, 'Cameroon', 0],
        [14, 'Uruguay', 1, 'South Korea', 0],
        [15, 'Portugal', 2, 'Ghana', 1],
        [16, 'Brazil', 3, 'Serbia', 1],
        [17, 'Iran', 1, 'Wales', 0],
        [18, 'Qatar', 0, 'Senegal', 1],
        [19, 'Netherlands', 2, 'Ecuador', 1],
        [20, 'England', 1, 'United States', 0],
        [21, 'Tunisia', 1, 'Australia', 1],
        [22, 'Poland', 3, 'Saudi Arabia', 0],
        [23, 'France', 0, 'Denmark', 1],
        [24, 'Argentina', 2, 'Mexico', 1],
        [25, 'Japan', 1, 'Costa Rica', 0],
        [26, 'Belgium', 2, 'Morocco', 1],
        [27, 'Croatia', 1, 'Canada', 0],
        [28, 'Spain', 0, 'Germany', 1],
        [29, 'Serbia', 1, 'Cameroon', 1],
        [30, 'South Korea', 1, 'Ghana', 0],
        [31, 'Brazil', 2, 'Switzerland', 1],
        [32, 'Portugal', 1, 'Uruguay', 0],
        [33, 'Ecuador', 0, 'Senegal', 1],
        [34, 'Netherlands', 2, 'Qatar', 0],
        [35, 'Iran', 0, 'United States', 1],
        [36, 'England', 2, 'Wales', 1],
        [37, 'Denmark', 2, 'Australia', 1],
        [38, 'Tunisia', 0, 'France', 2],
        [39, 'Poland', 0, 'Argentina', 2],
        [40, 'Saudi Arabia', 0, 'Mexico', 1],
        [41, 'Canada', 0, 'Morocco', 1],
        [42, 'Croatia', 1, 'Belguim', 2],
        [43, 'Costa Rica', 1, 'Germany', 3],
        [44, 'Japan', 1, 'Spain', 2],
        [45, 'Ghana', 1, 'Uruguay', 2],
        [56, 'South Korea', 0, 'Portugal', 2],
        [47, 'Brazil', 2, 'Cameroon', 0],
        [48, 'Serbia', 1, 'Switzerland', 2],
      ],
      points: 0,
    },
    {
      sheet: 'Sandy',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 2],
        [2, 'England', 4, 'Iran', 0],
        [1, 'Qatar', 0, 'Ecuador', 3],
        [4, 'United States', 1, 'Wales', 0],
        [5, 'Argentina', 4, 'Saudi Arabia', 0],
        [6, 'Denmark', 3, 'Tunisia', 0],
        [7, 'Mexico', 2, 'Poland', 1],
        [8, 'France', 3, 'Australia', 0],
        [9, 'Morocco', 0, 'Croatia', 2],
        [10, 'Germany', 3, 'Japan', 0],
        [11, 'Spain', 3, 'Costa Rica', 1],
        [12, 'Belgium', 3, 'Canada', 1],
        [13, 'Switzerland', 2, 'Cameroon', 1],
        [14, 'Uruguay', 3, 'South Korea', 1],
        [15, 'Portugal', 3, 'Ghana', 0],
        [16, 'Brazil', 4, 'Serbia', 0],
        [17, 'Iran', 0, 'Wales', 2],
        [18, 'Qatar', 0, 'Senegal', 3],
        [19, 'Netherlands', 3, 'Ecuador', 1],
        [20, 'England', 2, 'United States', 1],
        [21, 'Tunisia', 1, 'Australia', 2],
        [22, 'Poland', 2, 'Saudi Arabia', 0],
        [23, 'France', 2, 'Denmark', 1],
        [24, 'Argentina', 3, 'Mexico', 1],
        [25, 'Japan', 1, 'Costa Rica', 2],
        [26, 'Belgium', 4, 'Morocco', 1],
        [27, 'Croatia', 3, 'Canada', 1],
        [28, 'Spain', 1, 'Germany', 2],
        [29, 'Serbia', 3, 'Cameroon', 0],
        [30, 'South Korea', 2, 'Ghana', 1],
        [31, 'Brazil', 3, 'Switzerland', 1],
        [32, 'Portugal', 2, 'Uruguay', 1],
        [33, 'Ecuador', 1, 'Senegal', 3],
        [34, 'Netherlands', 4, 'Qatar', 0],
        [35, 'Iran', 0, 'United States', 3],
        [36, 'England', 2, 'Wales', 1],
        [37, 'Denmark', 3, 'Australia', 0],
        [38, 'Tunisia', 0, 'France', 2],
        [39, 'Poland', 0, 'Argentina', 3],
        [40, 'Saudi Arabia', 1, 'Mexico', 3],
        [41, 'Canada', 3, 'Morocco', 0],
        [42, 'Croatia', 1, 'Belguim', 3],
        [43, 'Costa Rica', 0, 'Germany', 3],
        [44, 'Japan', 0, 'Spain', 2],
        [45, 'Ghana', 0, 'Uruguay', 2],
        [56, 'South Korea', 1, 'Portugal', 2],
        [47, 'Brazil', 4, 'Cameroon', 0],
        [48, 'Serbia', 1, 'Switzerland', 3],
      ],
      points: 0,
    },
    {
      sheet: 'Dyl Ram',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 0, 'Netherlands', 2],
        [2, 'England', 2, 'Iran', 0],
        [1, 'Qatar', 2, 'Ecuador', 1],
        [4, 'United States', 2, 'Wales', 0],
        [5, 'Argentina', 3, 'Saudi Arabia', 0],
        [6, 'Denmark', 2, 'Tunisia', 0],
        [7, 'Mexico', 2, 'Poland', 0],
        [8, 'France', 2, 'Australia', 0],
        [9, 'Morocco', 0, 'Croatia', 3],
        [10, 'Germany', 3, 'Japan', 1],
        [11, 'Spain', 2, 'Costa Rica', 0],
        [12, 'Belgium', 2, 'Canada', 1],
        [13, 'Switzerland', 0, 'Cameroon', 1],
        [14, 'Uruguay', 0, 'South Korea', 2],
        [15, 'Portugal', 2, 'Ghana', 0],
        [16, 'Brazil', 4, 'Serbia', 0],
        [17, 'Iran', 0, 'Wales', 2],
        [18, 'Qatar', 2, 'Senegal', 0],
        [19, 'Netherlands', 3, 'Ecuador', 1],
        [20, 'England', 3, 'United States', 2],
        [21, 'Tunisia', 2, 'Australia', 1],
        [22, 'Poland', 1, 'Saudi Arabia', 0],
        [23, 'France', 3, 'Denmark', 1],
        [24, 'Argentina', 2, 'Mexico', 3],
        [25, 'Japan', 3, 'Costa Rica', 1],
        [26, 'Belgium', 2, 'Morocco', 0],
        [27, 'Croatia', 2, 'Canada', 0],
        [28, 'Spain', 1, 'Germany', 2],
        [29, 'Serbia', 0, 'Cameroon', 3],
        [30, 'South Korea', 2, 'Ghana', 1],
        [31, 'Brazil', 3, 'Switzerland', 1],
        [32, 'Portugal', 2, 'Uruguay', 1],
        [33, 'Ecuador', 0, 'Senegal', 1],
        [34, 'Netherlands', 2, 'Qatar', 1],
        [35, 'Iran', 0, 'United States', 3],
        [36, 'England', 2, 'Wales', 0],
        [37, 'Denmark', 2, 'Australia', 0],
        [38, 'Tunisia', 0, 'France', 3],
        [39, 'Poland', 1, 'Argentina', 3],
        [40, 'Saudi Arabia', 0, 'Mexico', 2],
        [41, 'Canada', 2, 'Morocco', 0],
        [42, 'Croatia', 1, 'Belguim', 3],
        [43, 'Costa Rica', 0, 'Germany', 2],
        [44, 'Japan', 1, 'Spain', 2],
        [45, 'Ghana', 1, 'Uruguay', 2],
        [56, 'South Korea', 2, 'Portugal', 3],
        [47, 'Brazil', 4, 'Cameroon', 1],
        [48, 'Serbia', 1, 'Switzerland', 3],
      ],
      points: 0,
    },
    {
      sheet: 'Mom',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 2],
        [2, 'England', 3, 'Iran', 0],
        [1, 'Qatar', 1, 'Ecuador', 2],
        [4, 'United States', 2, 'Wales', 1],
        [5, 'Argentina', 4, 'Saudi Arabia', 0],
        [6, 'Denmark', 2, 'Tunisia', 0],
        [7, 'Mexico', 1, 'Poland', 2],
        [8, 'France', 2, 'Australia', 0],
        [9, 'Morocco', 1, 'Croatia', 2],
        [10, 'Germany', 4, 'Japan', 0],
        [11, 'Spain', 3, 'Costa Rica', 1],
        [12, 'Belgium', 1, 'Canada', 0],
        [13, 'Switzerland', 2, 'Cameroon', 0],
        [14, 'Uruguay', 1, 'South Korea', 0],
        [15, 'Portugal', 3, 'Ghana', 0],
        [16, 'Brazil', 4, 'Serbia', 0],
        [17, 'Iran', 1, 'Wales', 3],
        [18, 'Qatar', 1, 'Senegal', 1],
        [19, 'Netherlands', 1, 'Ecuador', 0],
        [20, 'England', 2, 'United States', 1],
        [21, 'Tunisia', 0, 'Australia', 1],
        [22, 'Poland', 2, 'Saudi Arabia', 0],
        [23, 'France', 3, 'Denmark', 2],
        [24, 'Argentina', 4, 'Mexico', 1],
        [25, 'Japan', 0, 'Costa Rica', 1],
        [26, 'Belgium', 2, 'Morocco', 1],
        [27, 'Croatia', 2, 'Canada', 0],
        [28, 'Spain', 2, 'Germany', 3],
        [29, 'Serbia', 0, 'Cameroon', 1],
        [30, 'South Korea', 2, 'Ghana', 0],
        [31, 'Brazil', 2, 'Switzerland', 0],
        [32, 'Portugal', 2, 'Uruguay', 1],
        [33, 'Ecuador', 2, 'Senegal', 2],
        [34, 'Netherlands', 2, 'Qatar', 0],
        [35, 'Iran', 1, 'United States', 3],
        [36, 'England', 3, 'Wales', 0],
        [37, 'Denmark', 1, 'Australia', 0],
        [38, 'Tunisia', 0, 'France', 2],
        [39, 'Poland', 1, 'Argentina', 3],
        [40, 'Saudi Arabia', 0, 'Mexico', 2],
        [41, 'Canada', 1, 'Morocco', 0],
        [42, 'Croatia', 2, 'Belguim', 2],
        [43, 'Costa Rica', 0, 'Germany', 4],
        [44, 'Japan', 0, 'Spain', 3],
        [45, 'Ghana', 1, 'Uruguay', 2],
        [56, 'South Korea', 1, 'Portugal', 2],
        [47, 'Brazil', 3, 'Cameroon', 0],
        [48, 'Serbia', 0, 'Switzerland', 1],
      ],
      points: 0,
    },
    {
      sheet: 'Brosy',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 3],
        [2, 'England', 2, 'Iran', 0],
        [1, 'Qatar', 2, 'Ecuador', 1],
        [4, 'United States', 1, 'Wales', 1],
        [5, 'Argentina', 3, 'Saudi Arabia', 0],
        [6, 'Denmark', 3, 'Tunisia', 1],
        [7, 'Mexico', 2, 'Poland', 2],
        [8, 'France', 3, 'Australia', 1],
        [9, 'Morocco', 1, 'Croatia', 3],
        [10, 'Germany', 4, 'Japan', 1],
        [11, 'Spain', 2, 'Costa Rica', 1],
        [12, 'Belgium', 2, 'Canada', 0],
        [13, 'Switzerland', 3, 'Cameroon', 0],
        [14, 'Uruguay', 2, 'South Korea', 1],
        [15, 'Portugal', 3, 'Ghana', 0],
        [16, 'Brazil', 3, 'Serbia', 0],
        [17, 'Iran', 1, 'Wales', 3],
        [18, 'Qatar', 0, 'Senegal', 0],
        [19, 'Netherlands', 2, 'Ecuador', 0],
        [20, 'England', 2, 'United States', 0],
        [21, 'Tunisia', 1, 'Australia', 1],
        [22, 'Poland', 2, 'Saudi Arabia', 0],
        [23, 'France', 2, 'Denmark', 2],
        [24, 'Argentina', 3, 'Mexico', 1],
        [25, 'Japan', 2, 'Costa Rica', 1],
        [26, 'Belgium', 1, 'Morocco', 0],
        [27, 'Croatia', 2, 'Canada', 0],
        [28, 'Spain', 3, 'Germany', 3],
        [29, 'Serbia', 2, 'Cameroon', 0],
        [30, 'South Korea', 0, 'Ghana', 0],
        [31, 'Brazil', 3, 'Switzerland', 1],
        [32, 'Portugal', 2, 'Uruguay', 0],
        [33, 'Ecuador', 1, 'Senegal', 1],
        [34, 'Netherlands', 2, 'Qatar', 0],
        [35, 'Iran', 1, 'United States', 1],
        [36, 'England', 2, 'Wales', 1],
        [37, 'Denmark', 2, 'Australia', 0],
        [38, 'Tunisia', 1, 'France', 3],
        [39, 'Poland', 1, 'Argentina', 3],
        [40, 'Saudi Arabia', 1, 'Mexico', 3],
        [41, 'Canada', 2, 'Morocco', 2],
        [42, 'Croatia', 1, 'Belguim', 1],
        [43, 'Costa Rica', 1, 'Germany', 3],
        [44, 'Japan', 1, 'Spain', 4],
        [45, 'Ghana', 1, 'Uruguay', 1],
        [56, 'South Korea', 1, 'Portugal', 2],
        [47, 'Brazil', 3, 'Cameroon', 0],
        [48, 'Serbia', 1, 'Switzerland', 2],
      ],
      points: 0,
    },
    {
      sheet: 'Matt',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 2, 'Netherlands', 4],
        [2, 'England', 2, 'Iran', 0],
        [1, 'Qatar', 1, 'Ecuador', 2],
        [4, 'United States', 1, 'Wales', 1],
        [5, 'Argentina', 4, 'Saudi Arabia', 1],
        [6, 'Denmark', 5, 'Tunisia', 0],
        [7, 'Mexico', 1, 'Poland', 2],
        [8, 'France', 6, 'Australia', 0],
        [9, 'Morocco', 1, 'Croatia', 3],
        [10, 'Germany', 1, 'Japan', 0],
        [11, 'Spain', 3, 'Costa Rica', 0],
        [12, 'Belgium', 2, 'Canada', 0],
        [13, 'Switzerland', 2, 'Cameroon', 0],
        [14, 'Uruguay', 3, 'South Korea', 2],
        [15, 'Portugal', 4, 'Ghana', 0],
        [16, 'Brazil', 5, 'Serbia', 0],
        [17, 'Iran', 1, 'Wales', 1],
        [18, 'Qatar', 1, 'Senegal', 1],
        [19, 'Netherlands', 4, 'Ecuador', 1],
        [20, 'England', 2, 'United States', 0],
        [21, 'Tunisia', 1, 'Australia', 2],
        [22, 'Poland', 2, 'Saudi Arabia', 2],
        [23, 'France', 3, 'Denmark', 1],
        [24, 'Argentina', 2, 'Mexico', 0],
        [25, 'Japan', 3, 'Costa Rica', 0],
        [26, 'Belgium', 4, 'Morocco', 0],
        [27, 'Croatia', 2, 'Canada', 0],
        [28, 'Spain', 2, 'Germany', 2],
        [29, 'Serbia', 4, 'Cameroon', 2],
        [30, 'South Korea', 3, 'Ghana', 2],
        [31, 'Brazil', 3, 'Switzerland', 1],
        [32, 'Portugal', 4, 'Uruguay', 2],
        [33, 'Ecuador', 1, 'Senegal', 1],
        [34, 'Netherlands', 3, 'Qatar', 0],
        [35, 'Iran', 1, 'United States', 2],
        [36, 'England', 3, 'Wales', 1],
        [37, 'Denmark', 1, 'Australia', 0],
        [38, 'Tunisia', 0, 'France', 4],
        [39, 'Poland', 2, 'Argentina', 5],
        [40, 'Saudi Arabia', 1, 'Mexico', 2],
        [41, 'Canada', 2, 'Morocco', 0],
        [42, 'Croatia', 2, 'Belguim', 1],
        [43, 'Costa Rica', 1, 'Germany', 3],
        [44, 'Japan', 1, 'Spain', 3],
        [45, 'Ghana', 2, 'Uruguay', 2],
        [56, 'South Korea', 0, 'Portugal', 2],
        [47, 'Brazil', 4, 'Cameroon', 1],
        [48, 'Serbia', 3, 'Switzerland', 3],
      ],
      points: 0,
    },
    {
      sheet: 'Richie',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 2],
        [2, 'England', 1, 'Iran', 0],
        [1, 'Qatar', 2, 'Ecuador', 0],
        [4, 'United States', 1, 'Wales', 1],
        [5, 'Argentina', 3, 'Saudi Arabia', 1],
        [6, 'Denmark', 1, 'Tunisia', 0],
        [7, 'Mexico', 1, 'Poland', 0],
        [8, 'France', 2, 'Australia', 1],
        [9, 'Morocco', 1, 'Croatia', 1],
        [10, 'Germany', 1, 'Japan', 0],
        [11, 'Spain', 1, 'Costa Rica', 1],
        [12, 'Belgium', 0, 'Canada', 0],
        [13, 'Switzerland', 0, 'Cameroon', 0],
        [14, 'Uruguay', 2, 'South Korea', 0],
        [15, 'Portugal', 2, 'Ghana', 0],
        [16, 'Brazil', 2, 'Serbia', 1],
        [17, 'Iran', 0, 'Wales', 1],
        [18, 'Qatar', 1, 'Senegal', 0],
        [19, 'Netherlands', 1, 'Ecuador', 1],
        [20, 'England', 2, 'United States', 2],
        [21, 'Tunisia', 1, 'Australia', 1],
        [22, 'Poland', 1, 'Saudi Arabia', 0],
        [23, 'France', 2, 'Denmark', 0],
        [24, 'Argentina', 2, 'Mexico', 1],
        [25, 'Japan', 0, 'Costa Rica', 1],
        [26, 'Belgium', 0, 'Morocco', 0],
        [27, 'Croatia', 1, 'Canada', 0],
        [28, 'Spain', 2, 'Germany', 2],
        [29, 'Serbia', 1, 'Cameroon', 1],
        [30, 'South Korea', 1, 'Ghana', 1],
        [31, 'Brazil', 2, 'Switzerland', 0],
        [32, 'Portugal', 2, 'Uruguay', 2],
        [33, 'Ecuador', 1, 'Senegal', 0],
        [34, 'Netherlands', 2, 'Qatar', 2],
        [35, 'Iran', 0, 'United States', 1],
        [36, 'England', 2, 'Wales', 1],
        [37, 'Denmark', 1, 'Australia', 2],
        [38, 'Tunisia', 1, 'France', 3],
        [39, 'Poland', 1, 'Argentina', 3],
        [40, 'Saudi Arabia', 1, 'Mexico', 1],
        [41, 'Canada', 1, 'Morocco', 1],
        [42, 'Croatia', 2, 'Belguim', 1],
        [43, 'Costa Rica', 3, 'Germany', 3],
        [44, 'Japan', 2, 'Spain', 3],
        [45, 'Ghana', 1, 'Uruguay', 3],
        [56, 'South Korea', 0, 'Portugal', 2],
        [47, 'Brazil', 2, 'Cameroon', 1],
        [48, 'Serbia', 1, 'Switzerland', 1],
      ],
      points: 0,
    },
    {
      sheet: 'Dylina',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 0, 'Netherlands', 2],
        [2, 'England', 0, 'Iran', 1],
        [1, 'Qatar', 1, 'Ecuador', 1],
        [4, 'United States', 0, 'Wales', 2],
        [5, 'Argentina', 3, 'Saudi Arabia', 0],
        [6, 'Denmark', 2, 'Tunisia', 0],
        [7, 'Mexico', 0, 'Poland', 1],
        [8, 'France', 3, 'Australia', 1],
        [9, 'Morocco', 1, 'Croatia', 3],
        [10, 'Germany', 1, 'Japan', 1],
        [11, 'Spain', 2, 'Costa Rica', 0],
        [12, 'Belgium', 2, 'Canada', 2],
        [13, 'Switzerland', 2, 'Cameroon', 1],
        [14, 'Uruguay', 2, 'South Korea', 0],
        [15, 'Portugal', 0, 'Ghana', 1],
        [16, 'Brazil', 2, 'Serbia', 2],
        [17, 'Iran', 1, 'Wales', 1],
        [18, 'Qatar', 1, 'Senegal', 3],
        [19, 'Netherlands', 2, 'Ecuador', 2],
        [20, 'England', 1, 'United States', 1],
        [21, 'Tunisia', 3, 'Australia', 0],
        [22, 'Poland', 2, 'Saudi Arabia', 1],
        [23, 'France', 1, 'Denmark', 2],
        [24, 'Argentina', 2, 'Mexico', 1],
        [25, 'Japan', 1, 'Costa Rica', 0],
        [26, 'Belgium', 2, 'Morocco', 1],
        [27, 'Croatia', 3, 'Canada', 0],
        [28, 'Spain', 3, 'Germany', 2],
        [29, 'Serbia', 3, 'Cameroon', 0],
        [30, 'South Korea', 1, 'Ghana', 0],
        [31, 'Brazil', 3, 'Switzerland', 0],
        [32, 'Portugal', 2, 'Uruguay', 0],
        [33, 'Ecuador', 0, 'Senegal', 1],
        [34, 'Netherlands', 3, 'Qatar', 0],
        [35, 'Iran', 2, 'United States', 0],
        [36, 'England', 0, 'Wales', 0],
        [37, 'Denmark', 1, 'Australia', 1],
        [38, 'Tunisia', 1, 'France', 0],
        [39, 'Poland', 0, 'Argentina', 2],
        [40, 'Saudi Arabia', 1, 'Mexico', 0],
        [41, 'Canada', 1, 'Morocco', 2],
        [42, 'Croatia', 1, 'Belguim', 1],
        [43, 'Costa Rica', 1, 'Germany', 2],
        [44, 'Japan', 0, 'Spain', 2],
        [45, 'Ghana', 1, 'Uruguay', 2],
        [56, 'South Korea', 1, 'Portugal', 0],
        [47, 'Brazil', 5, 'Cameroon', 0],
        [48, 'Serbia', 4, 'Switzerland', 2],
      ],
      points: 0,
    },
    {
      sheet: 'Celest',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 0, 'Netherlands', 2],
        [2, 'England', 2, 'Iran', 0],
        [1, 'Qatar', 0, 'Ecuador', 1],
        [4, 'United States', 1, 'Wales', 1],
        [5, 'Argentina', 3, 'Saudi Arabia', 0],
        [6, 'Denmark', 1, 'Tunisia', 0],
        [7, 'Mexico', 2, 'Poland', 1],
        [8, 'France', 2, 'Australia', 1],
        [9, 'Morocco', 0, 'Croatia', 1],
        [10, 'Germany', 2, 'Japan', 0],
        [11, 'Spain', 1, 'Costa Rica', 0],
        [12, 'Belgium', 2, 'Canada', 1],
        [13, 'Switzerland', 2, 'Cameroon', 1],
        [14, 'Uruguay', 2, 'South Korea', 1],
        [15, 'Portugal', 2, 'Ghana', 0],
        [16, 'Brazil', 3, 'Serbia', 0],
        [17, 'Iran', 1, 'Wales', 2],
        [18, 'Qatar', 1, 'Senegal', 0],
        [19, 'Netherlands', 3, 'Ecuador', 1],
        [20, 'England', 2, 'United States', 1],
        [21, 'Tunisia', 2, 'Australia', 1],
        [22, 'Poland', 1, 'Saudi Arabia', 0],
        [23, 'France', 2, 'Denmark', 1],
        [24, 'Argentina', 2, 'Mexico', 3],
        [25, 'Japan', 3, 'Costa Rica', 1],
        [26, 'Belgium', 2, 'Morocco', 1],
        [27, 'Croatia', 1, 'Canada', 0],
        [28, 'Spain', 1, 'Germany', 2],
        [29, 'Serbia', 0, 'Cameroon', 2],
        [30, 'South Korea', 2, 'Ghana', 1],
        [31, 'Brazil', 3, 'Switzerland', 1],
        [32, 'Portugal', 2, 'Uruguay', 1],
        [33, 'Ecuador', 0, 'Senegal', 1],
        [34, 'Netherlands', 2, 'Qatar', 0],
        [35, 'Iran', 0, 'United States', 1],
        [36, 'England', 2, 'Wales', 1],
        [37, 'Denmark', 2, 'Australia', 1],
        [38, 'Tunisia', 0, 'France', 2],
        [39, 'Poland', 0, 'Argentina', 2],
        [40, 'Saudi Arabia', 1, 'Mexico', 2],
        [41, 'Canada', 1, 'Morocco', 0],
        [42, 'Croatia', 2, 'Belguim', 2],
        [43, 'Costa Rica', 0, 'Germany', 2],
        [44, 'Japan', 1, 'Spain', 2],
        [45, 'Ghana', 1, 'Uruguay', 2],
        [56, 'South Korea', 2, 'Portugal', 3],
        [47, 'Brazil', 3, 'Cameroon', 1],
        [48, 'Serbia', 1, 'Switzerland', 3],
      ],
      points: 0,
    },
    {
      sheet: 'Rich',
      rows: [
        ['id', 'home_team', 'home_score', 'away_team', 'away_score'],
        [3, 'Senegal', 1, 'Netherlands', 3],
        [2, 'England', 2, 'Iran', 0],
        [1, 'Qatar', 1, 'Ecuador', 2],
        [4, 'United States', 2, 'Wales', 1],
        [5, 'Argentina', 2, 'Saudi Arabia', 0],
        [6, 'Denmark', 2, 'Tunisia', 2],
        [7, 'Mexico', 3, 'Poland', 1],
        [8, 'France', 0, 'Australia', 2],
        [9, 'Morocco', 2, 'Croatia', 1],
        [10, 'Germany', 3, 'Japan', 0],
        [11, 'Spain', 2, 'Costa Rica', 1],
        [12, 'Belgium', 2, 'Canada', 0],
        [13, 'Switzerland', 1, 'Cameroon', 0],
        [14, 'Uruguay', 2, 'South Korea', 0],
        [15, 'Portugal', 2, 'Ghana', 0],
        [16, 'Brazil', 3, 'Serbia', 1],
        [17, 'Iran', 0, 'Wales', 1],
        [18, 'Qatar', 1, 'Senegal', 1],
        [19, 'Netherlands', 2, 'Ecuador', 1],
        [20, 'England', 2, 'United States', 1],
        [21, 'Tunisia', 1, 'Australia', 1],
        [22, 'Poland', 2, 'Saudi Arabia', 1],
        [23, 'France', 2, 'Denmark', 2],
        [24, 'Argentina', 2, 'Mexico', 1],
        [25, 'Japan', 2, 'Costa Rica', 1],
        [26, 'Belgium', 3, 'Morocco', 1],
        [27, 'Croatia', 2, 'Canada', 1],
        [28, 'Spain', 1, 'Germany', 1],
        [29, 'Serbia', 0, 'Cameroon', 0],
        [30, 'South Korea', 1, 'Ghana', 2],
        [31, 'Brazil', 2, 'Switzerland', 1],
        [32, 'Portugal', 2, 'Uruguay', 2],
        [33, 'Ecuador', 1, 'Senegal', 1],
        [34, 'Netherlands', 2, 'Qatar', 0],
        [35, 'Iran', 0, 'United States', 2],
        [36, 'England', 2, 'Wales', 0],
        [37, 'Denmark', 1, 'Australia', 0],
        [38, 'Tunisia', 0, 'France', 3],
        [39, 'Poland', 0, 'Argentina', 2],
        [40, 'Saudi Arabia', 0, 'Mexico', 2],
        [41, 'Canada', 2, 'Morocco', 1],
        [42, 'Croatia', 2, 'Belguim', 2],
        [43, 'Costa Rica', 0, 'Germany', 2],
        [44, 'Japan', 1, 'Spain', 2],
        [45, 'Ghana', 0, 'Uruguay', 1],
        [56, 'South Korea', 1, 'Portugal', 2],
        [47, 'Brazil', 3, 'Cameroon', 0],
        [48, 'Serbia', 1, 'Switzerland', 2],
      ],
      points: 0,
    },
  ];
  const results = [
    ['Senegal', 0, 'Netherlands', 2],
    ['England', 6, 'Iran', 2],
    ['Qatar', 0, 'Ecuador', 2],
    ['United States', 1, 'Wales', 1],
    ['Argentina', 1, 'Saudi Arabia', 2],
    ['Denmark', 0, 'Tunisia', 0],
    ['Mexico', 0, 'Poland', 0],
    ['France', 4, 'Australia', 1],
    ['Morocco', 0, 'Croatia', 0],
    ['Germany', 1, 'Japan', 2],
    ['Spain', 7, 'Costa Rica', 0],
    ['Belgium', 1, 'Canada', 0],
    ['Brazil', 2, 'Serbia', 0],
    ['Portugal', 3, 'Ghana', 2],
    ['Uruguay', 0, 'South Korea', 0],
    ['Switzerland', 1, 'Cameroon', 0],
    ['Iran', 2, 'Wales', 0],
    ['Qatar', 1, 'Senegal', 3],
    ['Netherlands', 1, 'Ecuador', 1],
    ['England', 0, 'United States', 0],
    ['Tunisia', 0, 'Australia', 1],
    ['Poland', 2, 'Saudi Arabia', 0],
    ['France', 2, 'Denmark', 1],
    ['Argentina', 2, 'Mexico', 0],
    ['Japan', 0, 'Costa Rica', 1],
    ['Belgium', 0, 'Morocco', 2],
    ['Croatia', 4, 'Canada', 1],
    ['Spain', 1, 'Germany', 1],
    ['Serbia', 3, 'Cameroon', 3],
    ['South Korea', 2, 'Ghana', 3],
    ['Brazil', 1, 'Switzerland', 0],
    ['Portugal', 2, 'Uruguay', 0],
    ['England', 3, 'Wales', 0],
    ['Iran', 0, 'United States', 1],
    ['Ecuador', 1, 'Senegal', 2],
    ['Netherlands', 2, 'Qatar', 0],
    ['Denmark', 0, 'Australia', 1],
    ['Tunisia', 1, 'France', 0,],
    ['Mexico', 2, 'Saudi Arabia', 1],
    ['Argentina', 2, 'Poland', 0]
  ];
  function searchResults(home_team, away_team) {
    for (result of results) {
      if (result.includes(home_team) && result.includes(away_team)) {
        return result;
      }
    }
  }

  for (user of picks) {
    console.log('');
    console.log(user.sheet);
    for (let t = 1; t < 41; t++) {
      let element = user.rows[t];
      let user_home_score = element[2];
      let user_away_score = element[4];
      let result = searchResults(element[1], element[3]);
      let result_home_score = result[result.indexOf(element[1])+1]
      let result_away_score = result[result.indexOf(element[3])+1];
      console.log('userscore= ' + element);
      console.log('resultscore= ' + result);
      console.log('');
      if (
        user_home_score === result_home_score &&
        user_away_score === result_away_score
      ) {
        console.log('YOU GOT 5 POINTS');
        console.log('');
        user.points += 5;
      } else {
        if (result_home_score > result_away_score) {
          if (user_home_score > user_away_score) {
            console.log('YOU GOT 3 POINTS');
            console.log('');
            user.points += 3;
          }
        } else if (result_away_score > result_home_score) {
          if (user_away_score > user_home_score) {
            console.log('YOU GOT 3 POINTS');
            console.log('');
            user.points += 3;
          }
        } else {
          if (user_away_score === user_home_score) {
            console.log('YOU GOT 3 POINTS');
            console.log('');
            user.points += 3;
          }
        }
      }
    }
  }

  picks.sort((a, b) => (a.points > b.points ? -1 : 1));
  const imageURL = __dirname + '/public/images/king.jpg';

  res.render('results', { Results: picks });
});

app.listen(process.env.PORT || 3000, function () {
  console.log('server running on port 3000');
});
